language: cpp

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - cmake
    - mesa-common-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libfontconfig1-dev
    - libfreetype6-dev
    - libsensors4-dev
    - libboost-dev

compiler:
 - gcc

branches:
  only:
    - development
    - master

before_script:
 - mkdir build
 - cd build
 - cmake ..

script:
 - make -j2
