language: cpp

sudo: false

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - build-essential
    - cmake
    - cmake-data
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - mesa-common-dev
    - libfontconfig1-dev

compiler:
 - gcc

branches:
  only:
    - development
    - master

before_script:
 - mkdir build
 - cd build
 - cmake ..

script:
 - make -j2
