git:
  depth: 1

language: cpp

compiler:
 - gcc

branches:
  only:
    - development
    - master

before_install:
 - sudo apt-get install build-essential cmake
 - sudo apt-get install mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev libfontconfig1-dev libfreetype6-dev libsensors4-dev libboost-dev

before_script:
 - mkdir build
 - cd build
 - cmake ..

script:
 - make -j2
